export enum IconName {
    Close = 'close',
    Delete = 'delete',
    Clear = 'clear',
    MusicNote = 'music_note',
    Search = 'search',
    Arrow = 'arrow_forward',
    History = 'history',
    Play = 'play_circle',
    Pause = 'pause_circle',
    Settings = 'settings',
    Minimize = 'close_fullscreen',
    Manufacturing = 'manufacturing',
    Info = 'info',
    Download = 'download',
    Random = 'random',
    Plus = 'plus',
    Learn = 'learn',
    Muscle = 'muscle',
    Tick = 'tick',
    Audio = 'audio',
    SignIn = 'sign_in',
    SignOut = 'sign_out',
}